CREATE TABLE IF NOT EXISTS minerwa_ingestion (
    id String,
    inBytes UInt32,
    inPkts UInt32,
    protocol UInt8,
    tcpFlags UInt8,
    l4SrcPort UInt16,
    ipv4SrcAddr IPv4,
    ipv6SrcAddr IPv6,
    l4DstPort UInt16,
    ipv4DstAddr IPv4,
    ipv6DstAddr IPv6,
    outBytes UInt32,
    outPkts UInt32,
    minIpPktLen UInt16,
    maxIpPktLen UInt16,
    icmpType UInt16,
    minTtl UInt8,
    maxTtl UInt8,
    direction UInt8,
    flowStartMilliseconds UInt64,
    flowEndMilliseconds UInt64,
    srcFragments UInt16,
    dstFragments UInt16,
    clientTcpFlags UInt8,
    serverTcpFlags UInt8,
    srcToDstAvgThroughput UInt32,
    dstToSrcAvgThroughput UInt32,
    numPktsUpTo128Bytes UInt32,
    numPkts128To256Bytes UInt32,
    numPkts256To512Bytes UInt32,
    numPkts512To1024Bytes UInt32,
    numPkts1024To1514Bytes UInt32,
    numPktsOver1514Bytes UInt32,
    srcIpCountry String,
    dstIpCountry String,
    srcIpLong String,
    srcIpLat String,
    dstIpLong String,
    dstIpLat String,
    longestFlowPkt UInt16,
    shortestFlowPkt UInt16,
    retransmittedInPkts UInt32,
    retransmittedOutPkts UInt32,
    ooorderInPkts UInt32,
    ooorderOutPkts UInt32,
    durationIn UInt32,
    durationOut UInt32,
    tcpWinMinIn UInt16,
    tcpWinMaxIn UInt16,
    tcpWinMssIn UInt16,
    tcpWinScaleIn UInt8,
    tcpWinMinOut UInt16,
    tcpWinMaxOut UInt16,
    tcpWinMssOut UInt16,
    tcpWinScaleOut UInt8,
    flowVerdict UInt16,
    srcToDstIatMin UInt32,
    srcToDstIatMax UInt32,
    srcToDstIatAvg UInt32,
    srcToDstIatStddev UInt32,
    dstToSrcIatMin UInt32,
    dstToSrcIatMax UInt32,
    dstToSrcIatAvg UInt32,
    dstToSrcIatStddev UInt32,
    applicationId UInt32
) ENGINE = NATS SETTINGS
    nats_url = 'nats://nats:4222',
    nats_subjects = 'minerwa.ingestion',
    nats_format = 'CapnProto',
    nats_schema = 'schema.capnp:Flow';


CREATE TABLE IF NOT EXISTS minerwa_flows (
    id UUID,
    inBytes UInt32,
    inPkts UInt32,
    protocol UInt8,
    tcpFlags UInt8,
    l4SrcPort UInt16,
    ipv4SrcAddr IPv4,
    ipv6SrcAddr IPv6,
    l4DstPort UInt16,
    ipv4DstAddr IPv4,
    ipv6DstAddr IPv6,
    outBytes UInt32,
    outPkts UInt32,
    minIpPktLen UInt16,
    maxIpPktLen UInt16,
    icmpType UInt16,
    minTtl UInt8,
    maxTtl UInt8,
    direction UInt8,
    flowStartMilliseconds UInt64,
    flowEndMilliseconds UInt64,
    srcFragments UInt16,
    dstFragments UInt16,
    clientTcpFlags UInt8,
    serverTcpFlags UInt8,
    srcToDstAvgThroughput UInt32,
    dstToSrcAvgThroughput UInt32,
    numPktsUpTo128Bytes UInt32,
    numPkts128To256Bytes UInt32,
    numPkts256To512Bytes UInt32,
    numPkts512To1024Bytes UInt32,
    numPkts1024To1514Bytes UInt32,
    numPktsOver1514Bytes UInt32,
    srcIpCountry String,
    dstIpCountry String,
    srcIpLong String,
    srcIpLat String,
    dstIpLong String,
    dstIpLat String,
    longestFlowPkt UInt16,
    shortestFlowPkt UInt16,
    retransmittedInPkts UInt32,
    retransmittedOutPkts UInt32,
    ooorderInPkts UInt32,
    ooorderOutPkts UInt32,
    durationIn UInt32,
    durationOut UInt32,
    tcpWinMinIn UInt16,
    tcpWinMaxIn UInt16,
    tcpWinMssIn UInt16,
    tcpWinScaleIn UInt8,
    tcpWinMinOut UInt16,
    tcpWinMaxOut UInt16,
    tcpWinMssOut UInt16,
    tcpWinScaleOut UInt8,
    flowVerdict UInt16,
    srcToDstIatMin UInt32,
    srcToDstIatMax UInt32,
    srcToDstIatAvg UInt32,
    srcToDstIatStddev UInt32,
    dstToSrcIatMin UInt32,
    dstToSrcIatMax UInt32,
    dstToSrcIatAvg UInt32,
    dstToSrcIatStddev UInt32,
    applicationId UInt32,
    dtc DateTime MATERIALIZED now()
) ENGINE = MergeTree()
  ORDER BY id
  TTL dtc + INTERVAL 1 HOUR;

CREATE MATERIALIZED VIEW IF NOT EXISTS minerwa_flows_mv TO minerwa_flows AS SELECT * FROM minerwa_ingestion;

SET allow_experimental_object_type=1;

CREATE TABLE IF NOT EXISTS minerwa_detections_nats (
    flow_id UUID NOT NULL,
    detector String NOT NULL,
    event_name String NOT NULL,
    metric Float32,
) ENGINE = NATS SETTINGS
    nats_url = 'nats://nats:4222',
    nats_subjects = 'minerwa.detection',
    nats_format = 'JSONEachRow';

CREATE TABLE IF NOT EXISTS minerwa_detections (
    flow_id UUID NOT NULL,
    detector String NOT NULL,
    event_name String NOT NULL,
    metric Float32,
    event_time DateTime NOT NULL DEFAULT now())
ENGINE = MergeTree()
ORDER BY flow_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS minerwa_detections_nats_mv TO minerwa_detections AS SELECT * FROM minerwa_detections_nats;

CREATE TABLE IF NOT EXISTS minerwa_detections_flows (
    flow_id UUID NOT NULL,
    ipv4SrcAddr IPv4,
    ipv4DstAddr IPv4,
    protocol UInt8,
    event_name String NOT NULL,
    detector String NOT NULL,
    metric Float32,
    event_time DateTime NOT NULL DEFAULT now())
ENGINE = MergeTree
ORDER BY flow_id;

CREATE MATERIALIZED VIEW IF NOT EXISTS minerwa_detections_mv TO minerwa_detections_flows
AS SELECT
    minerwa_flows.id as flow_id,
    minerwa_flows.ipv4SrcAddr,
    minerwa_flows.ipv4DstAddr,
    minerwa_flows.protocol,
    minerwa_detections.event_name,
    minerwa_detections.detector,
    minerwa_detections.metric,
    minerwa_detections.event_time as event_time
FROM minerwa_detections
JOIN minerwa_flows ON minerwa_flows.id = minerwa_detections.flow_id;
