version: '3'
services:
  ingestor:
    build: .
    volumes:
      - ./minerwa:/tmp/minerwa/minerwa:ro
      - ./config.conf:/etc/minerwa/minerwa.conf:ro
    command: ingestor
    depends_on:
      - nats
      - nprobe
  detector:
    build: .
    volumes:
      - ./minerwa:/tmp/minerwa/minerwa:ro
      - ./config.conf:/etc/minerwa/minerwa.conf:ro
      - ./scaling_config.yaml:/etc/minerwa/scaling_config.yaml:ro
      - ./sc3_bigsubset.attacks_binary-balanced.model.pkl:/etc/minerwa/filter_model.pkl:ro
      - ./final_model:/etc/minerwa/vae_model:ro
    command: detector
    depends_on:
      - nats
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  nprobe:
    image: ntop/nprobe
    command: '-i wlan0 --zmq tcp://0.0.0.0:5556 -n none --zmq-format j -T "%IN_BYTES %IN_PKTS %PROTOCOL %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %IPV6_SRC_ADDR %L4_DST_PORT %IPV4_DST_ADDR %IPV6_DST_ADDR %OUT_BYTES %OUT_PKTS %MIN_IP_PKT_LEN %MAX_IP_PKT_LEN %ICMP_TYPE %MIN_TTL %MAX_TTL %DIRECTION %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS %SRC_FRAGMENTS %DST_FRAGMENTS %CLIENT_TCP_FLAGS %SERVER_TCP_FLAGS %SRC_TO_DST_AVG_THROUGHPUT %DST_TO_SRC_AVG_THROUGHPUT %NUM_PKTS_UP_TO_128_BYTES %NUM_PKTS_128_TO_256_BYTES %NUM_PKTS_256_TO_512_BYTES %NUM_PKTS_512_TO_1024_BYTES %NUM_PKTS_1024_TO_1514_BYTES %NUM_PKTS_OVER_1514_BYTES %SRC_IP_COUNTRY %DST_IP_COUNTRY %SRC_IP_LONG %SRC_IP_LAT %DST_IP_LONG %DST_IP_LAT %LONGEST_FLOW_PKT %SHORTEST_FLOW_PKT %RETRANSMITTED_IN_PKTS %RETRANSMITTED_OUT_PKTS %OOORDER_IN_PKTS %OOORDER_OUT_PKTS %DURATION_IN %DURATION_OUT %TCP_WIN_MIN_IN %TCP_WIN_MAX_IN %TCP_WIN_MSS_IN %TCP_WIN_SCALE_IN %TCP_WIN_MIN_OUT %TCP_WIN_MAX_OUT %TCP_WIN_MSS_OUT %TCP_WIN_SCALE_OUT %FLOW_VERDICT %SRC_TO_DST_IAT_MIN %SRC_TO_DST_IAT_MAX %SRC_TO_DST_IAT_AVG %SRC_TO_DST_IAT_STDDEV %DST_TO_SRC_IAT_MIN %DST_TO_SRC_IAT_MAX %DST_TO_SRC_IAT_AVG %DST_TO_SRC_IAT_STDDEV %APPLICATION_ID"'
    network_mode: host
  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./schema.capnp:/var/lib/clickhouse/format_schemas/schema.capnp
    depends_on:
      - nats

networks:
  default:
    driver: bridge
