{
 "title": "Anomaly detection",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Current anomaly flows",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(flow_id) FROM \"default\".\"minerwa_detections\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Detected anomalies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(event_time) as time,  count(flow_id) malicious_flows FROM \"default\".\"minerwa_detections\" WHERE $__timeFilter(event_time) AND   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY time ORDER BY time ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "Top anomaly sources",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ipv4SrcAddr, count(flow_id) FROM \"default\".\"minerwa_detections_flows\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY ipv4SrcAddr ORDER BY count(flow_id) DESC LIMIT 100",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Anomaly by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT event_name, count(flow_id) FROM \"default\".\"minerwa_detections\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY event_name LIMIT 100"
    }
   ]
  },
  {
   "title": "Anomalies by detector",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT detector, count(flow_id) FROM \"default\".\"minerwa_detections\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY detector LIMIT 100"
    }
   ]
  },
  {
   "title": "Top protocols used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT protocol::text, count(protocol) FROM \"default\".\"minerwa_detections_flows\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY protocol LIMIT 100",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Top anomaly sources",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ipv4DstAddr, count(flow_id) FROM \"default\".\"minerwa_detections_flows\" WHERE   ( event_time  >= $__fromTime AND event_time <= $__toTime ) GROUP BY ipv4DstAddr ORDER BY count(flow_id) DESC LIMIT 100",
     "selectedFormat": 1
    }
   ]
  }
 ]
}