{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "sa" },
   { "name": "da" }
  ]
 },
 "panels": [
  {
   "title": "Ingested flows per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(dtc) as time, count(id)/60 as \"Flows per second\" FROM \"default\".\"minerwa_flows\" \nWHERE \n  $__timeFilter(dtc) \n  AND   ( dtc  >= $__fromTime AND dtc <= $__toTime ) \n  AND if('${sa}'!= '', ipv4SrcAddr == coalesce(nullIf('${sa}', ''), '0.0.0.0'), ''=='')\n  AND if('${da}'!= '', ipv4SrcAddr == coalesce(nullIf('${da}', ''), '0.0.0.0'), ''=='')  \nGROUP BY time ORDER BY time ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "Ingested packets per second (average per min)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute($__timeInterval(flowEndMilliseconds/1000)) as time, protocol::text, sum(inPkts)/60 as \"avg pkts/sec\" \nFROM \"default\".\"minerwa_flows\" \nWHERE \n  $__timeFilter_ms(flowEndMilliseconds) \n  AND ( flowEndMilliseconds/1000  >= $__fromTime AND flowEndMilliseconds/1000 <= $__toTime )\n  AND if('${sa}'!= '', ipv4SrcAddr == coalesce(nullIf('${sa}', ''), '0.0.0.0'), ''=='')\n  AND if('${da}'!= '', ipv4SrcAddr == coalesce(nullIf('${da}', ''), '0.0.0.0'), ''=='')\nGROUP BY time, protocol\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Ingested data volume per minute (average per min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT toStartOfMinute(dtc) as time, sum(inBytes/60) as \"avg B/sec\" FROM \"default\".\"minerwa_flows\" \nWHERE \n  $__timeFilter(dtc) \n  AND ( dtc  >= $__fromTime AND dtc <= $__toTime )\n  AND protocol = 6\n  AND if('${sa}'!= '', ipv4SrcAddr == coalesce(nullIf('${sa}', ''), '0.0.0.0'), ''=='')\n  AND if('${da}'!= '', ipv4SrcAddr == coalesce(nullIf('${da}', ''), '0.0.0.0'), ''=='')\nGROUP BY time ",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT toStartOfMinute(dtc) as time, sum(inBytes)/60 as \"avg B/sec\" FROM \"default\".\"minerwa_flows\" \nWHERE \n  $__timeFilter(dtc) \n  AND ( dtc  >= $__fromTime AND dtc <= $__toTime ) \n  AND protocol = 17\n  AND if('${sa}'!= '', ipv4SrcAddr == coalesce(nullIf('${sa}', ''), '0.0.0.0'), ''=='')\n  AND if('${da}'!= '', ipv4SrcAddr == coalesce(nullIf('${da}', ''), '0.0.0.0'), ''=='')\nGROUP BY time ",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT toStartOfMinute(dtc) as time, sum(inBytes/60) as \"avg B/sec\" FROM \"default\".\"minerwa_flows\" \nWHERE \n  $__timeFilter(dtc) \n  AND ( dtc  >= $__fromTime AND dtc <= $__toTime )\n  AND protocol != 6\n  AND protocol != 17\n  AND if('${sa}'!= '', ipv4SrcAddr == coalesce(nullIf('${sa}', ''), '0.0.0.0'), ''=='')\n  AND if('${da}'!= '', ipv4SrcAddr == coalesce(nullIf('${da}', ''), '0.0.0.0'), ''=='')\nGROUP BY time ",
     "selectedFormat": 4
    }
   ]
  }
 ]
}