--- 
- name: Estabilish victim wordpress site
  hosts: victim
  become: true
  vars:
    - WP_CACHE_PATH: "/var/cache/wordpress/"
    - WP_CACHE_FILE: "wp.tgz"
    - DB_USER: "root"
    - DB_PASSWD: "aJfvd5fgc124"
    - DB_WP_USER: "wpadmin"
    - DB_WP_USER_PASSWD: "aJfvd5fgc124"
  tasks:
    # install packages
    - name: Install packages for wordpress deploymnet
      apt:
        name: "{{item}}"
        update_cache: yes
        state: latest
      with_items:
        - apache2
        - apache2-utils 
        - mysql-client 
        - mysql-server
        - python3-mysqldb
        - php 
        - libapache2-mod-php 
        - php-mysql 
        - php-curl 
        - php-gd 
        - php-mbstring 
        - php-xml 
        - php-xmlrpc 
        - php-soap 
        - php-intl 
        - php-zip

      # mysql_secure_installation
    - name: Update DB root password
      mysql_user: 
        name: "{{DB_USER}}"
        host: "{{item}}"
        password: "{{DB_PASSWD}}"
        check_implicit_admin: yes
        login_user: "{{DB_USER}}"
        login_password: "{{DB_PASSWD}}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    # mysql_secure_installation
    - name: Delete anonymous MySQL user
      mysql_user: 
        name: "" 
        host: "{{item}}"
        state: "absent"
        login_user: "{{DB_USER}}"
        login_password: "{{DB_PASSWD}}"
      with_items:
        - localhost
        - "{{ansible_nodename}}"

      # mysql_secure_installation
    - name: Delete Hostname based MySQL user
      mysql_user:
        name: "{{DB_USER}}"
        host: "{{ansible_nodename}}"
        state: "absent"
        login_user: "{{DB_USER}}"
        login_password: "{{DB_PASSWD}}"

      # mysql_secure_installation
    - name: Remove MySQL test database
      mysql_db: 
        name: "test"
        state: "absent"
        login_user: "{{DB_USER}}"
        login_password: "{{DB_PASSWD}}"

    # setup wp db
    - name: setup wp db
      block:

        - name: create wp db
          mysql_db:
            name: "wp_myblog"
            state: "present"
            login_user: "{{DB_USER}}"
            login_password: "{{DB_PASSWD}}"  

        - name: create db wp user  
          mysql_user:
            name: "{{DB_WP_USER}}"
            password: "{{DB_WP_USER_PASSWD}}"
            state: "present"
            #priv: "db.wp_myblog:ALL"
            login_user: "{{DB_USER}}"
            login_password: "{{DB_PASSWD}}"

      tags: setup_db
          
    # download wordpress
    - name: download WP
      block:

        - name: ensure cache dir exists
          file:
            name: "{{WP_CACHE_PATH}}"
            state: directory

        - name: download WP
          get_url:
            url: "http://wordpress.org/latest.tar.gz"
            dest: "{{WP_CACHE_PATH}}/{{WP_CACHE_FILE}}"

        - name: extract & move to /var/www/html
          unarchive:
            src: "{{WP_CACHE_PATH}}/{{WP_CACHE_FILE}}"
            dest: "/var/www/html/"
            remote_src: yes
          

    # set wp config
    - name: set wp config
      template:
        src: "templates/wp_config_template.php.j2"
        dest: "/var/www/html/wordpress/wp-config.php"
      tags: wp_config_setup
      notify: 
        - Reload Apache
        - Restart mysql

    # - name: Create admin "test" account
    #   community.mysql.mysql_query:
    #     login_user: "{{DB_USER}}"
    #     login_password: "{{DB_PASSWD}}"
    #     login_db: "wp_myblog"
    #     query:
    #     - "INSERT INTO `wp_users` VALUES (1,'test','$P$BN/HtJx2.2If541j.WqC2C9wixV4am1','test','test@test.sk','http://192.168.121.120/wordpress','2022-07-20 09:32:55','',0,'test');"
    #     single_transaction: yes
    #   failed_when: false # never fail

    # - name: Set admin "test" metadata
    #   community.mysql.mysql_query:
    #     login_user: "{{DB_USER}}"
    #     login_password: "{{DB_PASSWD}}"
    #     login_db: "wp_usermeta"
    #     query:
    #     - "INSERT INTO `wp_usermeta` VALUES (1,1,'nickname','test'),(2,1,'first_name',''),(3,1,'last_name',''),(4,1,'description',''),(5,1,'rich_editing','true'),(6,1,'syntax_highlighting','true'),(7,1,'comment_shortcuts','false'),(8,1,'admin_color','fresh'),(9,1,'use_ssl','0'),(10,1,'show_admin_bar_front','true'),(11,1,'locale',''),(12,1,'wp_capabilities','a:1:{s:13:\"administrator\";b:1;}'),(13,1,'wp_user_level','10'),(14,1,'dismissed_wp_pointers',''),(15,1,'show_welcome_panel','1'),(16,1,'session_tokens',''),(17,1,'wp_dashboard_quick_press_last_post_id','4'),(18,1,'community-events-location','');"
    #     single_transaction: yes
    #   failed_when: false # never fail

  handlers:

  - name: general restart
    block:
      - name: Reload Apache
        service:
          name: apache2
          state: reloaded

      - name: Restart mysql
        service:
          name: mysql
          state: restarted
