[tool.poetry]
name = "vnet-nanodec"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{include = "vnet_nanodec"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
